In [3]:
import geopandas as gpd

In [4]:
states_shp = gpd.read_file("../temp/state/ne_10m_admin_1_states_provinces.shp", layer='ne_10m_admin_1_states_provinces')

In [5]:
states_shp.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 4596 entries, 0 to 4595
Columns: 121 entries, featurecla to geometry
dtypes: float64(12), geometry(1), int64(13), object(95)
memory usage: 4.2+ MB

In [6]:
filter_states = states_shp[["name", "adm1_code", "iso_3166_2", "fips", "type_en", "wikidataid", "latitude", "longitude","iso_a2"]]

In [7]:
filter_states

,name,adm1_code,iso_3166_2,fips,type_en,wikidataid,latitude,longitude,iso_a2
0,Entre Ríos,ARG-1309,AR-E,AR08,Province,Q44762,-32.02750,-59.2824,AR
1,Paysandú,URY-8,UY-PA,UY11,Department,Q16576,-32.09330,-57.2240,UY
2,Kalimantan Timur,IDN-1185,ID-KI,ID14,Province,Q3899,1.28915,116.3540,ID
3,Sabah,MYS-1186,MY-12,MY16,State,Q179029,5.31115,117.0950,MY
4,Arica y Parinacota,CHL-2694,CL-AP,None,Region,Q2109,-18.32070,-69.6804,CL
...,...,...,...,...,...,...,...,...,...
4591,Isla,MLT-5953,MT-20,None,None,Q846593,35.88640,14.5149,MT
4592,Cospicua,MLT-5955,MT-06,None,None,Q757225,35.88000,14.5207,MT
4593,Pietà,MLT-5942,MT-41,None,None,Q744070,35.88910,14.4927,MT
4594,Msida,MLT-5940,MT-34,None,None,Q585187,35.89490,14.4825,MT
4595,Birgu,MLT-5951,MT-03,None,None,Q752346,35.88710,14.5260,MT

In [18]:
filter_errors = filter_states['iso_a2']=='AT'

In [19]:
filter_states[filter_errors]

,name,adm1_code,iso_3166_2,fips,type_en,wikidataid,latitude,longitude,iso_a2
377,Niederösterreich,AUT-2330,AT-3,AU03,State,Q42497,48.2477,15.74480,AT
379,Oberösterreich,AUT-2326,AT-4,AU04,State,Q41967,48.2377,13.85600,AT
385,Burgenland,AUT-2322,AT-1,AU01,State,Q43210,47.4281,16.35840,AT
397,Vorarlberg,AUT-2320,AT-8,AU08,State,Q38981,47.2617,9.87375,AT
398,Tirol,AUT-2329,AT-7,AU07,State,Q42880,47.2082,11.38000,AT
588,Salzburg,AUT-2327,AT-5,AU05,State,Q43325,47.2534,13.01060,AT
590,Kärnten,AUT-2325,AT-2,AU02,State,Q37985,46.7201,13.86950,AT
789,Steiermark,AUT-2323,AT-6,AU06,State,Q41358,47.3901,14.85650,AT
3848,Wien,AUT-2331,AT-9,AU09,State,Q1741,48.2247,16.37980,AT